<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1576</name>
   <tag></tag>
   <elementGuidId>86b00f8e-aabb-4ffb-842a-5f4ea4605bf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1576</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1576']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6085cc57-e1d2-4cf9-988f-58983c3b853c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1576</value>
      <webElementGuid>63c5bc56-2eef-4f4e-8a3e-cb144999732e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>054d0bd4-60fb-4eaa-a456-a0953d4c2d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1576&quot;)</value>
      <webElementGuid>9399d654-757c-48b8-b9b9-a6127bd92364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1576']</value>
      <webElementGuid>dd6fde2c-23cf-471f-b3e0-333e64b61a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[3]/div/div/div/input</value>
      <webElementGuid>76c94733-1458-4eff-8652-c3c1835087e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>4079b0c8-de99-4ecb-b888-274fdba3bbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1576' and @type = 'text']</value>
      <webElementGuid>bdec6f86-f40b-4156-856e-101dd82647aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
