<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1573</name>
   <tag></tag>
   <elementGuidId>055ad83b-611b-47b0-b9cc-ebc4e8a39e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1573</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1573']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b053ff9-b2ee-4847-8d47-6ac1e8471cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1573</value>
      <webElementGuid>4185676d-74bc-4736-84f6-cfd49f79f82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9f02e9d-f26a-4e82-9ae8-019c34ddeeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1573&quot;)</value>
      <webElementGuid>c4d89346-b29b-452b-b1e5-28b7a053b9c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1573']</value>
      <webElementGuid>b1c21a6a-cfc8-479e-8084-f1286996d4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>f11d8063-b726-4fe2-a0cb-91e2625613d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>d42366b3-e2a8-4c4f-8dfd-a319d325480b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1573' and @type = 'text']</value>
      <webElementGuid>fda1e4de-dd43-4e8e-b2be-eb0b2ee70cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
