<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_input-1570</name>
   <tag></tag>
   <elementGuidId>8288cbfb-1451-4587-b653-43bd825e154f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1570</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1570']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94cd97ce-c107-4202-952e-75fe4423db45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1570</value>
      <webElementGuid>56e2af6e-7d0d-456e-8f8b-149d4edfd5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cbd45671-04c7-40b3-9c3c-0ff370f8d8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1570&quot;)</value>
      <webElementGuid>028c2ffd-9d2a-4620-b01e-064289950038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1570']</value>
      <webElementGuid>3cf7dd86-9570-4887-a329-98b3ef79a2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>a581ffc5-b902-43d6-8a10-4f65f3aadb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a7076db6-117d-41f8-8f6c-8d0415514e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1570' and @type = 'text']</value>
      <webElementGuid>c0bd2c33-ff2c-4b13-b75e-a77504e19b4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
